export const GET_PRODUCT_DETAIL_REQUEST = "GET_PRODUCT_DETAIL_REQUEST";
export const GET_PRODUCT_DETAIL_SUCCESS = "GET_PRODUCT_DETAIL_SUCCESS";
export const GET_PRODUCT_DETAIL_FAILED = "GET_PRODUCT_DETAIL_FAILED";
export const HANDLE_INCREMENT = "HANDLE_INCREMENT";
export const HANDLE_DECREMENT = "HANDLE_DECREMENT";
export const GET_LIST_PRODUCT_REQUEST = "GET_LIST_PRODUCT_REQUEST";
export const GET_LIST_PRODUCT_SUCCESS = "GET_LIST_PRODUCT_SUCCESS";
export const GET_LIST_PRODUCT_FAILED = "GET_LIST_PRODUCT_FAILED";