export const GET_LIST_PRODUCT_DETAIL_REQUEST = "GET_LIST_PRODUCT_DETAILREQUEST";
export const GET_LIST_PRODUCT_DETAIL_SUCCESS = "GET_LIST_PRODUCT_DETAIL_SUCCESS";
export const GET_LIST_PRODUCT_DETAIL_FAILED = "GET_LIST_PRODUCT_DETAIL_FAILED";