export const HANDLE_INIT_PRODUCT_TABS = "HANDLE_INIT_PRODUCT_TABS";
export const HANDLE_INIT_PRODUCT_INNER = "HANDLE_INIT_PRODUCT_INNER";


export const GET_LIST_PRODUCT_REQUEST = "GET_LIST_PRODUCT_REQUEST";
export const GET_LIST_PRODUCT_SUCCESS = "GET_LIST_PRODUCT_SUCCESS";
export const GET_LIST_PRODUCT_FAILED = "GET_LIST_PRODUCT_FAILED"